---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
  - package-ecosystem: terraform
    directory: /terraform
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
